import type { Lang } from '../../data/projects';

const en = {
  title: 'Full-stack developer course',
  shortTitle: 'Full-stack course',
  subtitle: 'React + Spring Boot, from zero to deployed',
  intro:
    'A free, practical path from “how does a website work?” to deploying your own full-stack application with React and Spring Boot. Every lesson ends with a short quiz and a hands-on exercise that runs right here in your browser.',
  modules: 'Modules',
  lessons: 'Lessons',
  hours: 'Hours',
  progress: 'Your progress',
  progressNote: 'Saved in this browser',
  start: 'Start the course',
  continue: 'Continue',
  continueLesson: 'Continue with',
  map: 'Progress map',
  moduleMap: 'Module map',
  showModuleMap: 'Show the module map',
  syllabus: 'Syllabus',
  module: 'Module',
  lesson: 'Lesson',
  min: 'min',
  soon: 'Coming soon',
  comingSoonModule: 'Lessons are being written. Support on Patreon to get them first.',
  project: 'Sample project',
  projectPatreon: 'Full source code on Patreon',
  practice: 'Practise in the interview simulator',
  done: 'Completed',
  completed: 'completed',
  markDone: 'Mark lesson as complete',
  markedDone: 'Lesson completed',
  undo: 'Undo',
  prev: 'Previous lesson',
  next: 'Next lesson',
  backToCourse: 'Course overview',
  inThisModule: 'In this module',
  takeaways: 'Key takeaways',
  notFound: 'This lesson does not exist yet.',
  loading: 'Loading lesson',
  langFallback: 'This lesson is not available in your language yet, so it is shown in the other one.',
  // quiz
  quiz: 'Check your understanding',
  quizIntro: 'Answer the questions — each one explains itself once you choose.',
  question: 'Question',
  correct: 'Correct',
  wrong: 'Not quite',
  score: 'Score',
  retry: 'Try again',
  best: 'Best',
  // exercise
  exercise: 'Exercise',
  run: 'Run tests',
  running: 'Running',
  reset: 'Reset code',
  showHint: 'Show hint',
  showSolution: 'Show solution',
  hideSolution: 'Hide solution',
  useSolution: 'Use this solution',
  output: 'Output',
  preview: 'Preview',
  tests: 'Tests',
  allPassed: 'All tests passed. Nice work!',
  someFailed: 'Some tests are still failing.',
  timeout: 'Your code did not finish in time — is there an endless loop?',
  noOutput: 'No console output.',
  editorLabel: 'Code editor',
  confirmReset: 'Replace your code with the starting code?',
  confirmSolution: 'Replace your code with the solution? Your current code will be lost.',
  editorShow: 'Open the code editor',
  // patreon
  patreonTitle: 'Get the sample projects',
  patreonText:
    'Each module comes with a real project: starter repo, finished source code and step-by-step notes. Supporters on Patreon get all of them, plus new lessons first.',
  patreonCta: 'Join on Patreon',
  free: 'Free',
  freeText: 'All lessons, quizzes and exercises',
  supporter: 'Patreon',
  supporterText: 'Sample projects, source code, early lessons',
  reset_progress: 'Reset progress',
  confirmResetProgress: 'Clear all your course progress in this browser?',
};

export type CourseText = typeof en;

const hu: CourseText = {
  title: 'Full-stack fejlesztő kurzus',
  shortTitle: 'Full-stack kurzus',
  subtitle: 'React + Spring Boot, a nulláról az élesítésig',
  intro:
    'Ingyenes, gyakorlatias út a „hogyan működik egy weboldal?” kérdéstől a saját, React és Spring Boot alapú full-stack alkalmazásod élesítéséig. Minden lecke egy rövid kvízzel és egy gyakorlati feladattal zárul, amely itt, a böngésződben fut.',
  modules: 'Modulok',
  lessons: 'Leckék',
  hours: 'Óra',
  progress: 'Haladásod',
  progressNote: 'Ebben a böngészőben mentve',
  start: 'Kezdd el a kurzust',
  continue: 'Folytatás',
  continueLesson: 'Folytasd ezzel:',
  map: 'Haladási térkép',
  moduleMap: 'A modul térképe',
  showModuleMap: 'A modul térképének megjelenítése',
  syllabus: 'Tanmenet',
  module: 'Modul',
  lesson: 'Lecke',
  min: 'perc',
  soon: 'Hamarosan',
  comingSoonModule: 'A leckék készülnek. Támogass a Patreonon, és elsőként kapod meg őket.',
  project: 'Mintaprojekt',
  projectPatreon: 'Teljes forráskód a Patreonon',
  practice: 'Gyakorolj az interjú-szimulátorban',
  done: 'Teljesítve',
  completed: 'teljesítve',
  markDone: 'Lecke megjelölése teljesítettként',
  markedDone: 'Lecke teljesítve',
  undo: 'Visszavonás',
  prev: 'Előző lecke',
  next: 'Következő lecke',
  backToCourse: 'Kurzus áttekintése',
  inThisModule: 'Ebben a modulban',
  takeaways: 'A legfontosabbak',
  notFound: 'Ez a lecke még nem létezik.',
  loading: 'Lecke betöltése',
  langFallback: 'Ez a lecke még nem érhető el a nyelveden, ezért a másik nyelven látod.',
  quiz: 'Ellenőrizd magad',
  quizIntro: 'Válaszolj a kérdésekre — választás után mindegyikhez magyarázat jár.',
  question: 'Kérdés',
  correct: 'Helyes',
  wrong: 'Nem egészen',
  score: 'Eredmény',
  retry: 'Újra',
  best: 'Legjobb',
  exercise: 'Gyakorlat',
  run: 'Tesztek futtatása',
  running: 'Futtatás',
  reset: 'Kód visszaállítása',
  showHint: 'Tipp mutatása',
  showSolution: 'Megoldás mutatása',
  hideSolution: 'Megoldás elrejtése',
  useSolution: 'Megoldás betöltése',
  output: 'Kimenet',
  preview: 'Előnézet',
  tests: 'Tesztek',
  allPassed: 'Minden teszt sikeres. Szép munka!',
  someFailed: 'Néhány teszt még nem sikeres.',
  timeout: 'A kódod nem futott le időben — nincs benne végtelen ciklus?',
  noOutput: 'Nincs konzolkimenet.',
  editorLabel: 'Kódszerkesztő',
  confirmReset: 'Lecseréled a kódodat a kiinduló kódra?',
  confirmSolution: 'Lecseréled a kódodat a megoldásra? A jelenlegi kódod elvész.',
  editorShow: 'Kódszerkesztő megnyitása',
  patreonTitle: 'Szerezd meg a mintaprojekteket',
  patreonText:
    'Minden modulhoz tartozik egy valódi projekt: kiinduló repó, kész forráskód és lépésenkénti jegyzetek. A Patreon-támogatók mindet megkapják, és az új leckéket is elsőként.',
  patreonCta: 'Csatlakozz a Patreonon',
  free: 'Ingyenes',
  freeText: 'Minden lecke, kvíz és gyakorlat',
  supporter: 'Patreon',
  supporterText: 'Mintaprojektek, forráskód, korai leckék',
  reset_progress: 'Haladás törlése',
  confirmResetProgress: 'Törlöd a teljes kurzushaladásodat ebben a böngészőben?',
};

const sk: CourseText = {
  title: 'Kurz full-stack vývoja',
  shortTitle: 'Full-stack kurz',
  subtitle: 'React + Spring Boot, od nuly až po nasadenie',
  intro:
    'Bezplatná praktická cesta od otázky „ako funguje web?“ až po nasadenie vlastnej full-stack aplikácie v Reacte a Spring Boote. Každá lekcia končí krátkym kvízom a praktickým cvičením, ktoré beží priamo tu, v tvojom prehliadači.',
  modules: 'Moduly',
  lessons: 'Lekcie',
  hours: 'Hodiny',
  progress: 'Tvoj postup',
  progressNote: 'Uložené v tomto prehliadači',
  start: 'Začni kurz',
  continue: 'Pokračovať',
  continueLesson: 'Pokračuj lekciou',
  map: 'Mapa postupu',
  moduleMap: 'Mapa modulu',
  showModuleMap: 'Zobraziť mapu modulu',
  syllabus: 'Osnova',
  module: 'Modul',
  lesson: 'Lekcia',
  min: 'min',
  soon: 'Čoskoro',
  comingSoonModule: 'Lekcie sa práve píšu. Podpor ma na Patreone a dostaneš ich ako prvý.',
  project: 'Vzorový projekt',
  projectPatreon: 'Kompletný zdrojový kód na Patreone',
  practice: 'Precvič si to v simulátore pohovoru',
  done: 'Dokončené',
  completed: 'dokončené',
  markDone: 'Označiť lekciu ako dokončenú',
  markedDone: 'Lekcia dokončená',
  undo: 'Vrátiť späť',
  prev: 'Predchádzajúca lekcia',
  next: 'Ďalšia lekcia',
  backToCourse: 'Prehľad kurzu',
  inThisModule: 'V tomto module',
  takeaways: 'Najdôležitejšie body',
  notFound: 'Táto lekcia zatiaľ neexistuje.',
  loading: 'Načítava sa lekcia',
  langFallback: 'Táto lekcia zatiaľ nie je dostupná v tvojom jazyku, preto ju vidíš v inom jazyku.',
  quiz: 'Over si, čo vieš',
  quizIntro: 'Odpovedz na otázky — po výbere sa ku každej zobrazí vysvetlenie.',
  question: 'Otázka',
  correct: 'Správne',
  wrong: 'Nie celkom',
  score: 'Skóre',
  retry: 'Skúsiť znova',
  best: 'Najlepšie',
  exercise: 'Cvičenie',
  run: 'Spustiť testy',
  running: 'Spúšťa sa',
  reset: 'Obnoviť kód',
  showHint: 'Zobraziť nápovedu',
  showSolution: 'Zobraziť riešenie',
  hideSolution: 'Skryť riešenie',
  useSolution: 'Použiť toto riešenie',
  output: 'Výstup',
  preview: 'Náhľad',
  tests: 'Testy',
  allPassed: 'Všetky testy prešli. Dobrá práca!',
  someFailed: 'Niektoré testy ešte neprechádzajú.',
  timeout: 'Tvoj kód nedobehol včas — nie je v ňom nekonečný cyklus?',
  noOutput: 'Žiadny výstup v konzole.',
  editorLabel: 'Editor kódu',
  confirmReset: 'Nahradiť tvoj kód počiatočným kódom?',
  confirmSolution: 'Nahradiť tvoj kód riešením? Tvoj aktuálny kód sa stratí.',
  editorShow: 'Otvoriť editor kódu',
  patreonTitle: 'Získaj vzorové projekty',
  patreonText:
    'Ku každému modulu patrí skutočný projekt: štartovací repozitár, hotový zdrojový kód a poznámky krok za krokom. Podporovatelia na Patreone dostanú všetky, a k tomu nové lekcie ako prví.',
  patreonCta: 'Pridaj sa na Patreone',
  free: 'Zadarmo',
  freeText: 'Všetky lekcie, kvízy a cvičenia',
  supporter: 'Patreon',
  supporterText: 'Vzorové projekty, zdrojový kód, lekcie v predstihu',
  reset_progress: 'Vynulovať postup',
  confirmResetProgress: 'Vymazať celý tvoj postup v kurze v tomto prehliadači?',
};

export const courseText: Record<Lang, CourseText> = { en, hu, sk };
