import type { Lang } from '../../data/projects';

/** the assistant's own words in both languages */
export const TEXT = {
  en: {
    launcher: 'Questions? Start a project',
    unread: '1 new message',
    teaser: 'Planning a website or app? Ask me anything — or get a project request ready in a minute.',
    teaserClose: 'Dismiss',
    title: 'Assistant',
    status: 'online · instant answers',
    close: 'Close chat',
    restart: 'Start over',
    placeholder: 'Type a question…',
    placeholderAnswer: 'Type your answer…',
    send: 'Send',
    disclosure: 'Automated assistant, no AI · nothing is stored until you send it',
    hello: 'Hi! I’m the assistant of softwaredevelopment.hu. I can answer questions about the services, projects and demos on this site — or put together a project request with you in about a minute.',
    helloHere: 'What would you like to do?',
    menu: { ask: 'Ask a question', order: 'Start a project', price: 'What does it cost?', demos: 'What can I try here?' },
    pickQuestion: 'Pick a question, or just type your own:',
    found: 'Here’s what I found:',
    alsoRelevant: 'Related on the site:',
    notSure: 'I’m not sure I got that. Did you mean one of these?',
    noMatch: 'I don’t have a ready answer for that. I can send your question to David — he usually replies within 24 hours.',
    human: 'Send my question to David',
    humanAsk: 'Sure. What’s your question? (If you already typed it, just send it again.)',
    humanEmail: 'What email address should the answer go to?',
    humanSent: 'Sent! You’ll get an answer by email, usually within 24 hours.',
    more: 'Anything else?',
    anythingElse: 'Ask something else',
    open: 'Open',
    read: 'Read',
    try: 'Try it',
    like: 'I want one like this',
    show: {
      services: 'Services',
      projects: 'Case studies',
      demos: 'Interactive demos',
      landings: 'Landing page demos',
      articles: 'Articles',
      stack: 'Technologies',
    },
    showIntro: {
      services: 'These are the main services:',
      projects: 'Some of the case studies:',
      demos: 'You can try these right here on the site:',
      landings: 'Ten landing pages for fictional brands, each full screen:',
      articles: 'Some articles that may help:',
      stack: 'The technologies used across the projects:',
    },
    context: {
      project: 'Ask about this project',
      similar: 'Something similar for me',
      landing: 'I want a site like this',
      modernize: 'Modernize my site',
      article: 'Related questions',
      course: 'About the course',
    },
    order: {
      start: 'Great — a few quick questions and your request is ready. You can skip anything.',
      interest: 'Noted your interest in',
      skip: 'Skip',
      done: 'Done',
      back: 'Back',
      step: 'Step',
      type: 'What are we building?',
      types: ['Website', 'Web app', 'E-commerce', 'Modernize existing site', 'Enterprise system', 'Other'],
      url: 'What’s the address of the current site?',
      urlPh: 'e.g. mysite.hu',
      budget: 'Roughly what budget do you have in mind?',
      budgets: ['< €1k', '€1–3k', '€3–8k', '€8–15k', '€15k+', 'Not sure yet'],
      timeline: 'When would you like it to be live?',
      timelines: ['ASAP', '1–3 months', '3+ months', 'Flexible'],
      features: 'Any must-haves? Pick all that apply, then press Done.',
      featureList: ['Online booking', 'Payments', 'Product catalogue', 'Blog / news', 'Multilingual', 'Content editing (CMS)', 'Search visibility (SEO)', 'User accounts', 'Integrations', 'AI features'],
      message: 'In a sentence or two: what should it achieve, or what is the problem today?',
      messagePh: 'e.g. more bookings, a faster site, replacing spreadsheets…',
      name: 'Almost done. What’s your name?',
      email: 'And your email address?',
      emailBad: 'That doesn’t look like an email address — could you check it?',
      phone: 'A phone number, if you prefer a call? (optional)',
      contactVia: 'How should David get in touch?',
      contactMethods: ['Email', 'Phone', 'Meeting'],
      company: 'Company name? (optional)',
      summary: 'Here’s your request — check it, then send:',
      labels: {
        type: 'type',
        url: 'url',
        budget: 'budget',
        timeline: 'timeline',
        features: 'must-haves',
        interest: 'interested in',
        message: 'goal',
        name: 'name',
        email: 'email',
        phone: 'phone',
        contact: 'contact via',
        company: 'company',
      },
      edit: 'Edit',
      sendIt: 'Send to David',
      sending: 'Sending…',
      sent: 'Sent! David usually replies within 24 hours. Anything else I can help with?',
      failed: 'Sorry, it could not be sent. Please try again, or write directly to',
      retry: 'Try again',
      resume: 'Continue my request',
      cancel: 'Cancel the request',
      cancelled: 'No problem — the request is cancelled. Ask me anything else.',
      inProgress: 'Back to your request:',
    },
  },
  hu: {
    launcher: 'Kérdésed van? Indíts projektet',
    unread: '1 új üzenet',
    teaser: 'Weboldalt vagy alkalmazást tervezel? Kérdezz bármit — vagy állítsd össze a megkeresésed egy perc alatt.',
    teaserClose: 'Bezárás',
    title: 'Asszisztens',
    status: 'online · azonnali válaszok',
    close: 'Csevegés bezárása',
    restart: 'Újrakezdés',
    placeholder: 'Írd be a kérdésed…',
    placeholderAnswer: 'Írd be a válaszod…',
    send: 'Küldés',
    disclosure: 'Automatikus asszisztens, MI nélkül · semmit nem tárolunk, amíg el nem küldöd',
    hello: 'Szia! A softwaredevelopment.hu asszisztense vagyok. Válaszolok az oldalon található szolgáltatásokkal, projektekkel és bemutatókkal kapcsolatos kérdésekre — vagy kb. egy perc alatt összeállítjuk együtt a projektmegkeresésed.',
    helloHere: 'Miben segíthetek?',
    menu: { ask: 'Kérdezek', order: 'Projektet indítok', price: 'Mennyibe kerül?', demos: 'Mit próbálhatok ki?' },
    pickQuestion: 'Válassz egy kérdést, vagy írd be a sajátodat:',
    found: 'Ezt találtam:',
    alsoRelevant: 'Kapcsolódó az oldalon:',
    notSure: 'Nem vagyok biztos benne, hogy jól értem. Ezek közül valamelyikre gondolsz?',
    noMatch: 'Erre nincs kész válaszom. Továbbíthatom a kérdésed Dávidnak — általában 24 órán belül válaszol.',
    human: 'Kérdés küldése Dávidnak',
    humanAsk: 'Rendben. Mi a kérdésed? (Ha már beírtad, küldd el újra.)',
    humanEmail: 'Milyen e-mail-címre menjen a válasz?',
    humanSent: 'Elküldve! E-mailben kapsz választ, általában 24 órán belül.',
    more: 'Segíthetek még valamiben?',
    anythingElse: 'Más kérdésem van',
    open: 'Megnyitás',
    read: 'Elolvasom',
    try: 'Kipróbálom',
    like: 'Ilyet szeretnék',
    show: {
      services: 'Szolgáltatások',
      projects: 'Esettanulmányok',
      demos: 'Interaktív bemutatók',
      landings: 'Bemutató oldalak',
      articles: 'Cikkek',
      stack: 'Technológiák',
    },
    showIntro: {
      services: 'A fő szolgáltatások:',
      projects: 'Néhány esettanulmány:',
      demos: 'Ezeket itt az oldalon ki is próbálhatod:',
      landings: 'Tíz bemutató oldal kitalált márkáknak, mind teljes képernyőn:',
      articles: 'Néhány cikk, ami segíthet:',
      stack: 'A projektekben használt technológiák:',
    },
    context: {
      project: 'Kérdésem van erről a projektről',
      similar: 'Hasonlót szeretnék',
      landing: 'Ilyen oldalt szeretnék',
      modernize: 'Az én oldalamat is modernizálnám',
      article: 'Kapcsolódó kérdések',
      course: 'A kurzusról',
    },
    order: {
      start: 'Remek — néhány gyors kérdés, és kész a megkeresésed. Bármit kihagyhatsz.',
      interest: 'Feljegyeztem, ami érdekel:',
      skip: 'Kihagyom',
      done: 'Kész',
      back: 'Vissza',
      step: 'Lépés',
      type: 'Mit építünk?',
      types: ['Weboldal', 'Webalkalmazás', 'Webshop', 'Meglévő oldal modernizálása', 'Vállalati rendszer', 'Egyéb'],
      url: 'Mi a jelenlegi oldal címe?',
      urlPh: 'pl. oldalam.hu',
      budget: 'Nagyjából milyen kerettel számolsz?',
      budgets: ['400 ezer Ft alatt', '400 ezer – 1,2 millió Ft', '1,2–3 millió Ft', '3–6 millió Ft', '6 millió Ft felett', 'Még nem tudom'],
      timeline: 'Mikorra szeretnéd élesben látni?',
      timelines: ['Minél előbb', '1–3 hónap', '3+ hónap', 'Rugalmas'],
      features: 'Mi az, ami mindenképp kell? Jelöld be, aztán nyomd meg a Kész gombot.',
      featureList: ['Online foglalás', 'Online fizetés', 'Termékkatalógus', 'Blog / hírek', 'Többnyelvűség', 'Tartalomszerkesztés (CMS)', 'Keresőoptimalizálás (SEO)', 'Felhasználói fiókok', 'Integrációk', 'MI-funkciók'],
      message: 'Egy-két mondatban: mit kellene elérnie, vagy mi ma a probléma?',
      messagePh: 'pl. több foglalás, gyorsabb oldal, Excel-táblák kiváltása…',
      name: 'Majdnem kész. Hogy hívnak?',
      email: 'És az e-mail-címed?',
      emailBad: 'Ez nem tűnik e-mail-címnek — megnéznéd még egyszer?',
      phone: 'Telefonszám, ha inkább hívást szeretnél? (nem kötelező)',
      contactVia: 'Hogyan vegye fel veled Dávid a kapcsolatot?',
      contactMethods: ['E-mail', 'Telefon', 'Találkozó'],
      company: 'Cégnév? (nem kötelező)',
      summary: 'Itt a megkeresésed — nézd át, aztán küldd el:',
      labels: {
        type: 'típus',
        url: 'cím',
        budget: 'keret',
        timeline: 'határidő',
        features: 'kell bele',
        interest: 'érdekli',
        message: 'cél',
        name: 'név',
        email: 'e-mail',
        phone: 'telefon',
        contact: 'kapcsolat',
        company: 'cég',
      },
      edit: 'Javítom',
      sendIt: 'Küldés Dávidnak',
      sending: 'Küldés…',
      sent: 'Elküldve! Dávid általában 24 órán belül válaszol. Segíthetek még valamiben?',
      failed: 'Sajnos nem sikerült elküldeni. Próbáld újra, vagy írj közvetlenül ide:',
      retry: 'Újrapróbálom',
      resume: 'Folytatom a megkeresést',
      cancel: 'Megkeresés elvetése',
      cancelled: 'Semmi gond — a megkeresést elvetettem. Kérdezz bármi mást.',
      inProgress: 'Vissza a megkereséshez:',
    },
  },
  sk: {
    launcher: 'Máte otázku? Začnite projekt',
    unread: '1 nová správa',
    teaser: 'Plánujete web alebo aplikáciu? Opýtajte sa na čokoľvek — alebo si za minútu pripravte dopyt na projekt.',
    teaserClose: 'Zavrieť',
    title: 'Asistent',
    status: 'online · okamžité odpovede',
    close: 'Zavrieť chat',
    restart: 'Začať odznova',
    placeholder: 'Napíšte otázku…',
    placeholderAnswer: 'Napíšte odpoveď…',
    send: 'Odoslať',
    disclosure: 'Automatický asistent bez AI · nič sa neukladá, kým to neodošlete',
    hello: 'Dobrý deň! Som asistent webu softwaredevelopment.hu. Odpoviem na otázky o službách, projektoch a ukážkach na tomto webe — alebo s vami asi za minútu pripravím dopyt na projekt.',
    helloHere: 'S čím vám môžem pomôcť?',
    menu: { ask: 'Mám otázku', order: 'Začať projekt', price: 'Koľko to stojí?', demos: 'Čo si tu môžem vyskúšať?' },
    pickQuestion: 'Vyberte si otázku alebo napíšte vlastnú:',
    found: 'Toto som našiel:',
    alsoRelevant: 'Súvisiace na webe:',
    notSure: 'Nie som si istý, či som vám dobre porozumel. Mysleli ste niektoré z týchto?',
    noMatch: 'Na toto nemám pripravenú odpoveď. Vašu otázku však môžem poslať Davidovi — zvyčajne odpovedá do 24 hodín.',
    human: 'Poslať otázku Davidovi',
    humanAsk: 'Jasné. Aká je vaša otázka? (Ak ste ju už napísali, pošlite ju ešte raz.)',
    humanEmail: 'Na akú e-mailovú adresu má prísť odpoveď?',
    humanSent: 'Odoslané! Odpoveď dostanete e-mailom, zvyčajne do 24 hodín.',
    more: 'Môžem pomôcť ešte s niečím?',
    anythingElse: 'Opýtať sa na niečo iné',
    open: 'Otvoriť',
    read: 'Prečítať',
    try: 'Vyskúšať',
    like: 'Chcem niečo podobné',
    show: {
      services: 'Služby',
      projects: 'Prípadové štúdie',
      demos: 'Interaktívne ukážky',
      landings: 'Ukážky landing pages',
      articles: 'Články',
      stack: 'Technológie',
    },
    showIntro: {
      services: 'Toto sú hlavné služby:',
      projects: 'Niekoľko prípadových štúdií:',
      demos: 'Tieto si môžete vyskúšať priamo na webe:',
      landings: 'Desať landing pages pre fiktívne značky, každá na celú obrazovku:',
      articles: 'Niekoľko článkov, ktoré môžu pomôcť:',
      stack: 'Technológie použité v projektoch:',
    },
    context: {
      project: 'Otázka k tomuto projektu',
      similar: 'Niečo podobné pre mňa',
      landing: 'Chcem takýto web',
      modernize: 'Modernizovať môj web',
      article: 'Súvisiace otázky',
      course: 'O kurze',
    },
    order: {
      start: 'Výborne — pár krátkych otázok a váš dopyt bude pripravený. Čokoľvek môžete preskočiť.',
      interest: 'Poznamenal som si váš záujem o',
      skip: 'Preskočiť',
      done: 'Hotovo',
      back: 'Späť',
      step: 'Krok',
      type: 'Čo budeme tvoriť?',
      types: ['Web', 'Webová aplikácia', 'E-shop', 'Modernizácia existujúceho webu', 'Podnikový systém', 'Iné'],
      url: 'Aká je adresa súčasného webu?',
      urlPh: 'napr. vasweb.sk',
      budget: 'S akým rozpočtom približne počítate?',
      budgets: ['< 1 000 €', '1 000 – 3 000 €', '3 000 – 8 000 €', '8 000 – 15 000 €', '15 000 €+', 'Zatiaľ neviem'],
      timeline: 'Kedy by mal byť spustený?',
      timelines: ['Čo najskôr', '1–3 mesiace', '3+ mesiace', 'Flexibilne'],
      features: 'Čo je nevyhnutné? Označte všetko, čo platí, a stlačte Hotovo.',
      featureList: ['Online rezervácie', 'Platby', 'Katalóg produktov', 'Blog / novinky', 'Viacjazyčnosť', 'Správa obsahu (CMS)', 'Viditeľnosť vo vyhľadávačoch (SEO)', 'Používateľské účty', 'Integrácie', 'Funkcie AI'],
      message: 'V jednej-dvoch vetách: čo by mal dosiahnuť, alebo aký je dnes problém?',
      messagePh: 'napr. viac rezervácií, rýchlejší web, náhrada tabuliek v Exceli…',
      name: 'Takmer hotovo. Ako sa voláte?',
      email: 'A vaša e-mailová adresa?',
      emailBad: 'Toto nevyzerá ako e-mailová adresa — môžete ju skontrolovať?',
      phone: 'Telefónne číslo, ak uprednostňujete hovor? (nepovinné)',
      contactVia: 'Ako vás má David kontaktovať?',
      contactMethods: ['E-mail', 'Telefón', 'Stretnutie'],
      company: 'Názov firmy? (nepovinné)',
      summary: 'Toto je váš dopyt — skontrolujte ho a odošlite:',
      labels: {
        type: 'typ',
        url: 'adresa',
        budget: 'rozpočet',
        timeline: 'termín',
        features: 'nevyhnutné',
        interest: 'záujem o',
        message: 'cieľ',
        name: 'meno',
        email: 'e-mail',
        phone: 'telefón',
        contact: 'kontakt cez',
        company: 'firma',
      },
      edit: 'Upraviť',
      sendIt: 'Odoslať Davidovi',
      sending: 'Odosiela sa…',
      sent: 'Odoslané! David zvyčajne odpovedá do 24 hodín. Môžem vám pomôcť ešte s niečím?',
      failed: 'Prepáčte, odoslanie sa nepodarilo. Skúste to znova alebo napíšte priamo na',
      retry: 'Skúsiť znova',
      resume: 'Pokračovať v dopyte',
      cancel: 'Zrušiť dopyt',
      cancelled: 'Žiadny problém — dopyt je zrušený. Opýtajte sa na čokoľvek iné.',
      inProgress: 'Späť k vášmu dopytu:',
    },
  },
} satisfies Record<Lang, unknown>;

export type Text = (typeof TEXT)['en'];
