import type { Lang } from '../../data/projects';
import type { Density, Entry, SectionKind } from './model';

/** headings printed on the CV, in the CV's own language */
export const headings: Record<Lang, Record<SectionKind, string> & { contact: string; present: string }> = {
  en: {
    summary: 'Profile',
    experience: 'Experience',
    education: 'Education',
    skills: 'Skills',
    languages: 'Languages',
    certifications: 'Certifications',
    projects: 'Projects',
    custom: 'Additional information',
    contact: 'Contact',
    present: 'Present',
  },
  hu: {
    summary: 'Szakmai profil',
    experience: 'Szakmai tapasztalat',
    education: 'Tanulmányok',
    skills: 'Készségek',
    languages: 'Nyelvtudás',
    certifications: 'Tanúsítványok',
    projects: 'Projektek',
    custom: 'További információk',
    contact: 'Elérhetőség',
    present: 'jelenleg',
  },
};

type FieldText = Partial<Record<keyof Entry, string>>;

const en = {
  title: 'CV Maker',
  subtitle: 'Build a professional CV',
  intro:
    'Build a clean, professional CV step by step and see it take shape as you type. Choose a layout, reorder the sections, then save it as a PDF. Everything stays in your browser — nothing is uploaded.',
  back: 'All projects',
  guideLink: 'How to write a strong CV',
  saved: 'Saved in this browser',
  tabs: { edit: 'Edit', preview: 'Preview' },
  step: 'Step',
  of: 'of',
  prev: 'Back',
  next: 'Next',
  steps: { profile: 'Profile', contact: 'Contact & links', structure: 'Sections', design: 'Layout', export: 'Export' },
  stepText: {
    profile: 'Your name, the role you are aiming for and, if you want one, a photo.',
    contact: 'How a recruiter reaches you — and where they can see your work.',
    structure: 'Choose which sections appear on the CV and in what order. Put the most relevant ones first.',
    design: 'Pick one of {n} layouts and an accent colour. The content stays the same; only the presentation changes.',
    export: 'Check the result, then save it as a PDF or keep a backup of your data.',
  },
  name: 'Full name',
  namePh: 'Anna Kovács',
  headline: 'Professional title',
  headlinePh: 'Senior Frontend Developer',
  photo: 'Photo',
  photoHint: 'Optional. A recent, neutral headshot. Leave it out for markets or roles where photos are not expected.',
  photoUpload: 'Upload photo',
  photoChange: 'Change',
  photoRemove: 'Remove',
  photoError: 'This image could not be read. Try a JPG or PNG.',
  email: 'Email',
  emailPh: 'anna.kovacs@email.com',
  phone: 'Phone',
  phonePh: '+36 30 123 4567',
  location: 'Location',
  locationPh: 'Budapest, Hungary',
  links: 'Links',
  linksHint: 'LinkedIn, GitHub, portfolio — only links that help your application.',
  linkLabel: 'Label',
  linkLabelPh: 'LinkedIn',
  linkUrl: 'Address',
  linkUrlPh: 'linkedin.com/in/annakovacs',
  addLink: 'Add link',
  sectionTitle: 'Heading on the CV',
  sectionTitleHint: 'Leave empty for the default heading.',
  text: 'Text',
  summaryPh:
    'Frontend developer with 7 years of experience building data-heavy web applications in React and TypeScript. Led the rebuild of a banking dashboard used by 40,000 customers…',
  summaryHint: '3–4 sentences: who you are, your strongest experience, and what you bring to this role.',
  customPh: 'A short paragraph, or leave it empty and use entries below.',
  addEntry: 'Add entry',
  entry: 'Entry',
  untitled: 'Untitled',
  moveUp: 'Move up',
  moveDown: 'Move down',
  remove: 'Remove',
  edit: 'Edit',
  done: 'Done',
  hide: 'Remove section',
  addSection: 'Add a section',
  kindNames: {
    summary: 'Professional summary',
    experience: 'Work experience',
    education: 'Education',
    skills: 'Skills',
    languages: 'Languages',
    certifications: 'Certifications',
    projects: 'Projects',
    custom: 'Custom section',
  } as Record<SectionKind, string>,
  kindHints: {
    summary: 'A short pitch at the top of the CV.',
    experience: 'Jobs, most recent first.',
    education: 'Degrees and relevant courses.',
    skills: 'Tools and abilities, optionally with a level.',
    languages: 'Languages and how well you speak them.',
    certifications: 'Certificates and licences.',
    projects: 'Side projects, open source, notable work.',
    custom: 'Volunteering, awards, publications — anything else.',
  } as Record<SectionKind, string>,
  fields: {
    experience: { title: 'Job title', subtitle: 'Company', place: 'Location', start: 'Start', end: 'End', current: 'I currently work here', description: 'Achievements' },
    education: { title: 'Degree / qualification', subtitle: 'School', place: 'Location', start: 'Start', end: 'End', description: 'Details' },
    skills: { title: 'Skill', subtitle: 'Group (optional)', level: 'Level' },
    languages: { title: 'Language', subtitle: 'Level description', level: 'Level' },
    certifications: { title: 'Certificate', subtitle: 'Issuer', end: 'Date', url: 'Link / ID' },
    projects: { title: 'Project name', subtitle: 'Role / technologies', url: 'Link', start: 'Start', end: 'End', description: 'What you did' },
    custom: { title: 'Title', subtitle: 'Organisation', start: 'Start', end: 'End', description: 'Details' },
    summary: {},
  } as Record<SectionKind, FieldText>,
  placeholders: {
    experience: { title: 'Frontend Developer', subtitle: 'Acme Ltd.', place: 'Budapest', start: '03/2021', end: '06/2024', description: '- Cut page load time by 45% by introducing code splitting\n- Led a team of 3 developers…' },
    education: { title: 'BSc Computer Science', subtitle: 'Budapest University of Technology', place: 'Budapest', start: '2014', end: '2018', description: 'Thesis: …' },
    skills: { title: 'TypeScript', subtitle: 'Frontend' },
    languages: { title: 'English', subtitle: 'C1 — fluent' },
    certifications: { title: 'AWS Certified Developer', subtitle: 'Amazon Web Services', end: '2024', url: '' },
    projects: { title: 'Budget tracker app', subtitle: 'React, Firebase', url: 'github.com/…', start: '2023', end: '', description: '- Built and released an app used by 2,000 people' },
    custom: { title: 'Volunteer mentor', subtitle: 'Code Club', start: '2022', end: '', description: '' },
    summary: {},
  } as Record<SectionKind, FieldText>,
  descHint: 'One point per line. Start with an action verb and add a number where you can.',
  levelNone: 'Hide level',
  levels: ['Basic', 'Elementary', 'Intermediate', 'Advanced', 'Expert'],
  template: 'Layout',
  layoutsAll: 'All',
  layoutGroups: { modern: 'Modern', creative: 'Creative', classic: 'Classic' },
  atsBadge: 'ATS-friendly',
  prevLayout: 'Previous layout',
  nextLayout: 'Next layout',
  accent: 'Accent colour',
  density: 'Spacing',
  densities: { compact: 'Compact', normal: 'Normal', airy: 'Airy' } as Record<Density, string>,
  showPhoto: 'Show photo',
  cvLang: 'CV headings language',
  pdf: 'Save as PDF',
  pdfHint:
    'Opens the print dialog. Choose “Save as PDF” as the destination, paper size A4, and switch off “Headers and footers” for a clean result. The text stays selectable, so applicant tracking systems can read it.',
  print: 'Print',
  backup: 'Your data',
  backupHint: 'Your CV is saved automatically in this browser. Download a backup file to move it to another device or keep versions for different applications.',
  download: 'Download backup (.json)',
  importFile: 'Load backup',
  importError: 'This file is not a CV backup.',
  example: 'Load example',
  blank: 'Start blank',
  confirmReset: 'This replaces your current CV. Continue?',
  checklist: 'Before you send it',
  checks: {
    name: 'Name and professional title filled in',
    contact: 'Email or phone number added',
    summary: 'A professional summary of 2–5 sentences',
    experience: 'At least one job or project with achievements',
    numbers: 'At least one measurable result (a number or %)',
    length: 'Fits on about two pages',
  },
  pages: 'Estimated length',
  page: 'page',
  pagesPlural: 'pages',
  exampleNote: 'You are looking at an example CV. Replace the text with your own, or start from a blank page.',
  tipLabel: 'Tip',
  readMore: 'Read more in the guide',
  tips: {
    profile: 'Use the job title you are applying for, not a vague one. “Senior Java Developer” beats “IT professional”.',
    contact: 'A professional email address and one or two relevant links are enough. A full street address is not needed.',
    structure: 'Experienced? Lead with experience. Fresh graduate? Put education and projects first.',
    design: 'Applying through an online portal? The ATS plain layout is the safest choice for automatic screening.',
    export: 'Name the file clearly, e.g. “Anna-Kovacs-CV-Frontend.pdf”.',
    summary: 'Write it last — it is easier once the rest of the CV is done.',
    experience: 'Describe results, not duties: what changed because you were there?',
    education: 'Once you have a few years of experience, keep this short.',
    skills: 'List the skills the job ad asks for first. Skip obvious ones like “Microsoft Word”.',
    languages: 'Use the CEFR scale (A1–C2) where you can — recruiters across Europe understand it.',
    certifications: 'Only current, relevant certificates. Add an ID or link so they can be verified.',
    projects: 'Great for career changers and juniors: show what you built and what it achieved.',
    custom: 'Volunteering, awards or publications — only if they strengthen the application.',
  } as Record<string, string>,
  /** which guide topic each step's tip links to */
  tipTarget: {
    profile: 'tailor',
    contact: 'personal',
    structure: 'relevance',
    design: 'ats',
    export: 'proofread',
    summary: 'summary',
    experience: 'achievements',
    education: 'relevance',
    skills: 'relevance',
    languages: 'consistency',
    certifications: 'relevance',
    projects: 'achievements',
    custom: 'concise',
  } as Record<string, string>,
};

export type CvText = typeof en;

const hu: CvText = {
  title: 'Önéletrajz-készítő',
  subtitle: 'Profi önéletrajz lépésről lépésre',
  intro:
    'Készíts letisztult, profi önéletrajzot lépésről lépésre, és nézd, ahogy gépelés közben formát ölt. Válassz elrendezést, rendezd át a szakaszokat, majd mentsd el PDF-ként. Minden adat a böngésződben marad — semmit nem töltünk fel.',
  back: 'Összes projekt',
  guideLink: 'Hogyan írj jó önéletrajzot',
  saved: 'Mentve ebben a böngészőben',
  tabs: { edit: 'Szerkesztés', preview: 'Előnézet' },
  step: 'Lépés',
  of: '/',
  prev: 'Vissza',
  next: 'Tovább',
  steps: { profile: 'Profil', contact: 'Elérhetőség', structure: 'Szakaszok', design: 'Megjelenés', export: 'Exportálás' },
  stepText: {
    profile: 'A neved, a megcélzott pozíció és — ha szeretnél — egy fotó.',
    contact: 'Hogyan ér el a toborzó, és hol láthatja a munkáidat.',
    structure: 'Válaszd ki, mely szakaszok kerüljenek az önéletrajzba, és milyen sorrendben. A legfontosabbak legyenek elöl.',
    design: 'Válassz a {n} elrendezés közül, és adj meg kiemelőszínt. A tartalom ugyanaz marad, csak a megjelenés változik.',
    export: 'Nézd át az eredményt, aztán mentsd PDF-ként, vagy készíts biztonsági másolatot az adataidról.',
  },
  name: 'Teljes név',
  namePh: 'Kovács Anna',
  headline: 'Szakmai titulus',
  headlinePh: 'Senior frontend fejlesztő',
  photo: 'Fotó',
  photoHint: 'Nem kötelező. Friss, semleges portré. Hagyd el, ha az adott piacon vagy pozíciónál nem szokás.',
  photoUpload: 'Fotó feltöltése',
  photoChange: 'Csere',
  photoRemove: 'Törlés',
  photoError: 'Ezt a képet nem sikerült beolvasni. Próbálj JPG-t vagy PNG-t.',
  email: 'E-mail',
  emailPh: 'kovacs.anna@email.hu',
  phone: 'Telefon',
  phonePh: '+36 30 123 4567',
  location: 'Lakhely',
  locationPh: 'Budapest',
  links: 'Linkek',
  linksHint: 'LinkedIn, GitHub, portfólió — csak olyan link, ami erősíti a jelentkezést.',
  linkLabel: 'Megnevezés',
  linkLabelPh: 'LinkedIn',
  linkUrl: 'Cím',
  linkUrlPh: 'linkedin.com/in/kovacsanna',
  addLink: 'Link hozzáadása',
  sectionTitle: 'Címsor az önéletrajzon',
  sectionTitleHint: 'Hagyd üresen az alapértelmezett címsorhoz.',
  text: 'Szöveg',
  summaryPh:
    'Frontend fejlesztő 7 év tapasztalattal adatintenzív webalkalmazások fejlesztésében React és TypeScript alapon. Vezettem egy 40 000 ügyfél által használt banki felület újraírását…',
  summaryHint: '3–4 mondat: ki vagy, mi a legerősebb tapasztalatod, és mit hozol ebbe a pozícióba.',
  customPh: 'Egy rövid bekezdés, vagy hagyd üresen és használd a lenti tételeket.',
  addEntry: 'Tétel hozzáadása',
  entry: 'Tétel',
  untitled: 'Névtelen',
  moveUp: 'Feljebb',
  moveDown: 'Lejjebb',
  remove: 'Törlés',
  edit: 'Szerkesztés',
  done: 'Kész',
  hide: 'Szakasz eltávolítása',
  addSection: 'Szakasz hozzáadása',
  kindNames: {
    summary: 'Szakmai összefoglaló',
    experience: 'Szakmai tapasztalat',
    education: 'Tanulmányok',
    skills: 'Készségek',
    languages: 'Nyelvtudás',
    certifications: 'Tanúsítványok',
    projects: 'Projektek',
    custom: 'Egyéni szakasz',
  },
  kindHints: {
    summary: 'Rövid bemutatkozás az önéletrajz tetején.',
    experience: 'Munkahelyek, a legfrissebbel kezdve.',
    education: 'Végzettségek és releváns képzések.',
    skills: 'Eszközök és képességek, opcionálisan szinttel.',
    languages: 'Nyelvek és azok szintje.',
    certifications: 'Tanúsítványok és engedélyek.',
    projects: 'Saját projektek, open source, kiemelt munkák.',
    custom: 'Önkéntesség, díjak, publikációk — bármi más.',
  },
  fields: {
    experience: { title: 'Munkakör', subtitle: 'Cég', place: 'Helyszín', start: 'Kezdés', end: 'Befejezés', current: 'Jelenleg is itt dolgozom', description: 'Eredmények' },
    education: { title: 'Végzettség / képesítés', subtitle: 'Intézmény', place: 'Helyszín', start: 'Kezdés', end: 'Befejezés', description: 'Részletek' },
    skills: { title: 'Készség', subtitle: 'Csoport (opcionális)', level: 'Szint' },
    languages: { title: 'Nyelv', subtitle: 'Szint leírása', level: 'Szint' },
    certifications: { title: 'Tanúsítvány', subtitle: 'Kiállító', end: 'Dátum', url: 'Link / azonosító' },
    projects: { title: 'Projekt neve', subtitle: 'Szerep / technológiák', url: 'Link', start: 'Kezdés', end: 'Befejezés', description: 'Mit csináltál' },
    custom: { title: 'Megnevezés', subtitle: 'Szervezet', start: 'Kezdés', end: 'Befejezés', description: 'Részletek' },
    summary: {},
  },
  placeholders: {
    experience: { title: 'Frontend fejlesztő', subtitle: 'Példa Kft.', place: 'Budapest', start: '2021/03', end: '2024/06', description: '- 45%-kal csökkentettem az oldalbetöltési időt code splitting bevezetésével\n- 3 fős fejlesztőcsapatot vezettem…' },
    education: { title: 'Mérnökinformatikus BSc', subtitle: 'Budapesti Műszaki és Gazdaságtudományi Egyetem', place: 'Budapest', start: '2014', end: '2018', description: 'Szakdolgozat: …' },
    skills: { title: 'TypeScript', subtitle: 'Frontend' },
    languages: { title: 'Angol', subtitle: 'C1 — tárgyalóképes' },
    certifications: { title: 'AWS Certified Developer', subtitle: 'Amazon Web Services', end: '2024', url: '' },
    projects: { title: 'Költségkövető alkalmazás', subtitle: 'React, Firebase', url: 'github.com/…', start: '2023', end: '', description: '- 2000 felhasználó által használt alkalmazást építettem és adtam ki' },
    custom: { title: 'Önkéntes mentor', subtitle: 'Code Club', start: '2022', end: '', description: '' },
    summary: {},
  },
  descHint: 'Soronként egy pont. Kezdd cselekvő igével, és ahol lehet, adj meg számot.',
  levelNone: 'Szint elrejtése',
  levels: ['Alap', 'Kezdő', 'Középhaladó', 'Haladó', 'Szakértő'],
  template: 'Elrendezés',
  layoutsAll: 'Mind',
  layoutGroups: { modern: 'Modern', creative: 'Kreatív', classic: 'Klasszikus' },
  atsBadge: 'ATS-barát',
  prevLayout: 'Előző elrendezés',
  nextLayout: 'Következő elrendezés',
  accent: 'Kiemelőszín',
  density: 'Térköz',
  densities: { compact: 'Sűrű', normal: 'Normál', airy: 'Levegős' },
  showPhoto: 'Fotó megjelenítése',
  cvLang: 'Az önéletrajz címsorainak nyelve',
  pdf: 'Mentés PDF-ként',
  pdfHint:
    'Megnyílik a nyomtatási ablak. Célként válaszd a „Mentés PDF-ként” lehetőséget, A4-es papírméretet, és kapcsold ki a „Fejlécek és láblécek” opciót. A szöveg kijelölhető marad, így a jelentkeztető rendszerek is be tudják olvasni.',
  print: 'Nyomtatás',
  backup: 'Az adataid',
  backupHint:
    'Az önéletrajzod automatikusan mentődik ebben a böngészőben. Tölts le biztonsági másolatot, ha másik eszközön folytatnád, vagy külön verziót tartanál meg egy-egy jelentkezéshez.',
  download: 'Biztonsági másolat letöltése (.json)',
  importFile: 'Másolat betöltése',
  importError: 'Ez a fájl nem önéletrajz-mentés.',
  example: 'Példa betöltése',
  blank: 'Üres lap',
  confirmReset: 'Ez felülírja a jelenlegi önéletrajzodat. Folytatod?',
  checklist: 'Mielőtt elküldöd',
  checks: {
    name: 'Név és szakmai titulus kitöltve',
    contact: 'E-mail-cím vagy telefonszám megadva',
    summary: '2–5 mondatos szakmai összefoglaló',
    experience: 'Legalább egy munkahely vagy projekt eredményekkel',
    numbers: 'Legalább egy mérhető eredmény (szám vagy %)',
    length: 'Nagyjából két oldalba belefér',
  },
  pages: 'Becsült terjedelem',
  page: 'oldal',
  pagesPlural: 'oldal',
  exampleNote: 'Ez egy minta önéletrajz. Írd át a saját adataidra, vagy kezdd üres lappal.',
  tipLabel: 'Tipp',
  readMore: 'Bővebben az útmutatóban',
  tips: {
    profile: 'Azt a pozíciót írd ide, amire jelentkezel. A „Senior Java fejlesztő” jobb, mint az „IT szakember”.',
    contact: 'Elég egy professzionális e-mail-cím és egy-két releváns link. Pontos lakcímre nincs szükség.',
    structure: 'Van tapasztalatod? Az kerüljön előre. Pályakezdő vagy? Kezdj a tanulmányokkal és a projektekkel.',
    design: 'Online felületen jelentkezel? Az ATS-barát elrendezés a legbiztosabb az automatikus szűréshez.',
    export: 'Adj beszédes fájlnevet, pl. „Kovacs-Anna-oneletrajz-frontend.pdf”.',
    summary: 'A végén írd meg — könnyebb, ha a többi rész már kész.',
    experience: 'Eredményeket írj, ne feladatokat: mi változott attól, hogy ott voltál?',
    education: 'Néhány év tapasztalat után ez legyen rövid.',
    skills: 'Az álláshirdetésben kért készségek kerüljenek előre. A „Microsoft Word” típusú magától értetődőket hagyd ki.',
    languages: 'Ha lehet, használd a KER-skálát (A1–C2) — Európa-szerte érthető.',
    certifications: 'Csak érvényes, releváns tanúsítványt. Adj meg azonosítót vagy linket az ellenőrizhetőséghez.',
    projects: 'Pályaváltóknak és pályakezdőknek kiváló: mutasd meg, mit építettél, és mit ért el.',
    custom: 'Önkéntesség, díjak, publikációk — csak ha erősítik a jelentkezést.',
  },
  tipTarget: en.tipTarget,
};

export const cvText: Record<Lang, CvText> = { en, hu };
